#!/bin/bash

# Install dependencies
apt update
apt install -y curl make git build-essential

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Clone upstream
rm -rf /data/upstream
mkdir -p /data/upstream
git clone https://github.com/metanorma/ruby-packer.git /data/upstream

# Checkout latest release
cd /data/upstream
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

# Install dependencies
make

# Build upstream (see https://github.com/metanorma/ruby-packer/blob/master/bin/build-linux.sh)
apt-get update -y && apt-get install -y squashfs-tools bison flex texinfo
echo "debconf debconf/frontend select Noninteractive" | debconf-set-selections
export TEMP_DIR="$(mktemp -d /tmp/.rubyc-build.XXXXXX)"
cp -r * $TEMP_DIR
bin/rubyc --clean-tmpdir -r "$TEMP_DIR" -o rubyc "$TEMP_DIR/bin/rubyc"
strip rubyc

# Copy binaries to staging directory
mkdir -p /data/staging
cp rubyc /data/staging/rubyc-linux.$(uname -m)
