#!/bin/bash

# Install dependencies
apt update
apt install -y curl make git build-essential gnupg2 procps texinfo squashfs-tools squashfs-tools bison flex

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install and active the Ruby Version Manager
gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh

# Install Ruby version
rvm install 2.5.1
rvm use 2.5.1

# Clone upstream
rm -rf /data/upstream
mkdir -p /data/upstream
git clone https://github.com/metanorma/ruby-packer.git /data/upstream

# Checkout latest release
cd /data/upstream
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

# Build upstream (see https://github.com/metanorma/ruby-packer/blob/master/bin/build-linux.sh)
make
export TEMP_DIR="$(mktemp -d .rubyc-build)"
cp -r * $TEMP_DIR
bin/rubyc --clean-tmpdir -r "$TEMP_DIR" -o rubyc "$TEMP_DIR/bin/rubyc"
strip rubyc

# Copy binaries to staging directory
mkdir -p /data/staging
cp rubyc /data/staging/rubyc-linux.$(uname -m)
